rmq:
  image: rabbitmq:3.5.4-management
  ports:
    - "15672:15672"
    - "5672:5672"
  environment:
    RABBITMQ_DEFAULT_USER: jcarley
    RABBITMQ_DEFAULT_PASS: letmein123
  labels:
    com.example.description: "rmq"

