rmq:
  image: rabbitmq:3.5.4-management
  ports:
    - "15672:15672"
    - "5672:5672"
  environment:
    RABBITMQ_DEFAULT_USER: dev
    RABBITMQ_DEFAULT_PASS: dev
  labels:
    com.example.description: "rmq"

